apiVersion: apps/v1
kind: Deployment
metadata:
  name: webForProject4
spec:
  selector:
    matchLabels:
      name: webForProject4
  template:
    metadata:
      labels:
        name: webForProject4
    spec:
      containers:
      - name: webForProject4
        image: hungdq1379/docker1379:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
      imagePullSecrets:
      - name: ciond-project4
